### PR TITLE
Vote for cheeaun

### PR DESCRIPTION
**Pull request by huei90**
I vote for @cheeaun to being an awesome hacker.

I love the project [life](https://github.com/cheeaun/life) he built!

And also lot of [Awesome Projects](http://cheeaun.com/projects/)!

:+1: 

---

| profile pic | name | reason | source
|:---------:|:------------:|:------------:|:------------:
|  | cheeaun | cheeaun has a great project [life](https://github.com/cheeaun/life), it's awesome! |  [Github](https://github.com/cheeaun), [cheeaun.com](http://cheeaun.com)

### CODE REVIEW

**Comment by huei90** [comment]
@cheeaun I vote for your project life.

**Comment by sayanee** [comment]
:+1: thank you @cheeaun for awesome projects  :heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Comment by llun** [comment]
:+1:

**Comment by huei90** [comment]
One more left and @cheeaun will be the first in [awesome-hacker](https://github.com/huei90/awesome-hacker)!

It's awesome!

**Comment by prathamesh-sonpatki** [comment]
@cheeaun :heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart: you are awesome hacker!

**Comment by huei90** [comment]
Awesome! @cheeaun the first one in Awesome-Hacker!!

Congratulation :congratulations:

**Comment by notthetup** [comment]
:+1:

**Comment by Valentine** [comment]
👍

**Pull request merged**
