### PR TITLE
Vote for sindresorhus

### PR DESCRIPTION
**Pull request by huei90**
Everyone knows him. No need word for him :smile: Vote for him. @sindresorhus

---

| profile pic | name | reason | source
|:---------:|:------------:|:------------:|:------------:
|  | sindresorhus | No need to say, he's awesome! |  [Github](https://github.com/sindresorhus)

### CODE REVIEW

**Comment by huei90** [comment]
@sindresorhus is awesome!

**Comment by cheeaun** [comment]
:+1:

**Comment by llun** [comment]
:+1:

**Comment by notthetup** [comment]
:+1:

**Comment by sindresorhus** [comment]
:-1: I'm not interested in participating in dumb popularity contests. Please don't include me.

**Comment by huei90** [comment]
Thanks for your comment and sorry for bothering you.
I will close this conversation thread and you won't get any notification further.

**Pull request closed without merging**
